version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=mysql
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    ports:
      - "6379:6379"